[tool.poetry]
name = "indiana-docs"
version = "1.2.0"
description = ""
authors = ["James Turk <james@openstates.org>"]

[tool.poetry.dependencies]
python = "^3.7"
Flask = "^1.1"
requests = "^2.22"
waitress = "^1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
