name: Test Python

on:
  push:
    - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Python & dependency installation
    - uses: actions/checkout@v3
    - name: setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: install Poetry
      uses: snok/install-poetry@v1.1.1
    - name: install dependencies
      run: poetry install
    - name: lint with flake8
      run: poetry run flake8 --show-source --statistics .
    - name: lint with black
      run: poetry run black --check --diff .
